layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
    facebook: your_username
    hackerrank: darshan_aswani
    instagram: darshan_aswani
  # keybase: your_username
    linkedin: darshan-aswani
    medium: darshanaswani63
    stackoverflow: your_user_id
  # telegram: your_username
    twitter: darshanaswani63
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/cpp/cpp.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Algorithm
    web_url: https://github.com/topics/algorithm

  - name: javascript
    web_url: https://github.com/topics/javscript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png
